import type { NextComponentType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import Header from "../components/Header";
import { Flex, Switch } from "@chakra-ui/react";

import {
  Slider,
  SliderTrack,
  SliderFilledTrack,
  SliderThumb,
  SliderMark,
} from "@chakra-ui/react";
const starterOffers = [
  "10,000 Visitors",
  "Create Unlimited Widgets",
  "All Widget Types",
  "3rd party Integration",
  "Advanced targeting",
  "Widget A/B Testing",
];
const proOffers = [
  "10,000 Visitors",
  "Create Unlimited Widgets",
  "All Widget Types",
  "3rd party Integration",
  "Advanced targeting",
  "Widget A/B Testing",
  "Priority Support",
];
const enterpriceOffers = [
  "10,000 Visitors",
  "Create Unlimited Widgets",
  "All Widget Types",
  "3rd party Integration",
  "Advanced targeting",
  "Widget A/B Testing",
];
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pricing UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center bg-[rgb(245,247,249)] min-h-screen">
        <Header />
        <h1 className="text-5xl pt-16 text-center ">Choose your plan</h1>
        <p className="text-xl text-gray-600 py-6 text-center">
          14 days unlimited free trail. No contract or credit card required.
        </p>
        <Flex
          alignItems={"center"}
          width="270px"
          justifyContent="space-between"
        >
          <p className="font-medium">Monthly</p>
          <Switch></Switch>
          <p className="text-gray-500 font-medium">Yearly</p>
          <p className="text-blue-400 text-sm border-blue-400 py-1 px-2 rounded-3xl border-2">
            20% OFF
          </p>
        </Flex>
        <div className="w-2/4 max-[800px]:w-10/12">
          <p className="mb-3 font-bold  uppercase text-xs text-gray-400 mt-4">
            Number of month visitors
          </p>
          <Slider
            aria-label="slider-ex-1"
            defaultValue={2000}
            min={0}
            max={10000}
            step={1000}
          >
            <SliderTrack>
              <SliderFilledTrack />
            </SliderTrack>
            <SliderThumb />
          </Slider>
        </div>
        <Flex
          width="70%"
          justifyContent="space-between"
          className="mt-8 max-[800px]:flex-col"
        >
          <PriceCard
            name={"Starter"}
            price="29"
            offers={starterOffers}
            bg="white"
          />
          <PriceCard name={"Pro"} price="46" offers={proOffers} bg="gray" />
          <PriceCard
            name={"Enterprice"}
            price="99"
            offers={enterpriceOffers}
            bg="white"
          />
        </Flex>
      </main>
    </div>
  );
};

function PriceCard(props: any) {
  return props.bg == "white" ? (
    <Flex
      direction={"column"}
      alignItems="center"
      textAlign={"center"}
      flex="1"
      backgroundColor={"white"}
      marginX="10px"
      marginTop="20px"
      marginBottom={"20px"}
      paddingY={"50px"}
      rounded="15px"
      shadow={"lg"}
    >
      <h3 className="font-bold text-xl">{props.name}</h3>
      <div className="flex items-center mb-4">
        <h1 className="font-bold text-4xl inline">${props.price}</h1>
        <span className="text-gray-400 text-xs font-medium">/MO</span>
      </div>
      {props.offers.map((item: string, index: number) => {
        return (
          <div className="flex items-center mt-3 w-10/12" key={index}>
            <Image
              src="/assets/tick.png"
              alt="tick-img"
              width="40"
              height="40"
              className="px-2"
            />
            <p>{item}</p>
          </div>
        );
      })}
      <button className="uppercase bg-blue-600 px-6 py-3 mt-8 text-white rounded text-sm font-medium">
        Get Started
      </button>
    </Flex>
  ) : (
    <Flex
      direction={"column"}
      alignItems="center"
      textAlign={"center"}
      flex="1"
      borderTop={"35px blue solid"}
      backgroundColor={"gray.800"}
      marginX="10px"
      marginTop="0px"
      paddingY={"50px"}
      rounded="15px"
      shadow={"lg"}
      color={"white"}
    >
      <h3 className="font-bold text-xl">{props.name}</h3>
      <div className="flex items-center mb-4">
        <h1 className="font-bold text-4xl inline">${props.price}</h1>
        <span className="text-gray-400 text-xs font-medium">/MO</span>
      </div>
      {props.offers.map((item: string, index: number) => {
        return (
          <div className="flex items-center mt-3 w-10/12" key={index}>
            <Image
              src="/assets/tick.png"
              alt="tick-img"
              width="40"
              height="40"
              className="px-2"
            />
            <p>{item}</p>
          </div>
        );
      })}
      <button className="uppercase bg-blue-600 px-6 py-3 mt-8 text-white rounded text-sm font-medium">
        Get Started
      </button>
    </Flex>
  );
}

export default Home;
